name       : python-adapt-parser
version    : 0.3.7
release    : 5
source     :
    - https://pypi.io/packages/source/a/adapt-parser/adapt-parser-0.3.7.tar.gz : ec04e7f40c3b16f34b797fb8d4ab8e27248f4e4a0b1ecfbb20a013c77ce33341
license    : Apache-2.0
component  : programming.python
summary    : The Adapt Intent Parser is a flexible and extensible intent definition and determination framework
description: |
    Adapt is an intent parser – meaning that it is a library for converting natural language into machine-readable data structures, such as JSON. The Adapt Intent Parser is open source software. It is lightweight and is designed to run on devices with limited computing resources, such as embedded devices.
builddeps  :
    - python-six
    - python-pyee
rundeps    :
    - python-six
    - python-pyee
setup      : |
    # No way we are allowing fixed versions!
    sed -i -e 's|==|>=|g' setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
